server:
  port: 8080
  contextPath: /mlearningportal
---
spring:
  profiles: default,local
  jpa:
    hibernate:
      ddl-auto: none
      
  http:
    multipart:
        max-file-size: 800MB
        max-request-size: 800MB
  mvc: 
    view:
      prefix:  /WEB-INF/jsp/
      suffix: .jsp 

LOG_PATH: logs/
UPLOAD_PATH_USER_IMG: USER_IMG
UPLOAD_PATH_CONTENT_SLIDES:  CONTENT_SLIDES
UPLOAD_PATH_CONTENT_AUDIO:  CONTENT_AUDIO
UPLOAD_PATH_COURSE_IMG: COURSE_IMG

datasource:

    url: jdbc:mysql://localhost:3306/cinfysys_mlearningDB
    username: root
    password: root@123
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema: 
    maxPoolSize: 50
    removeAbandoned: true
    removeAbandonedTimeout: 120
    logAbandoned: true
    maxActive: 50
    maxIdle: 5
    maxWait: 1000
    validationQuery: "select 1"
    testOnBorrow: true
    testOnConnect: true
    testWhileIdle: true
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect




   
    
    